"""ToolTether stable public API."""

from .constants import PROJECT_VERSION as __version__
from .errors import (
    AdapterError,
    MissingExtraError,
    StorageError,
    ToolApprovalError,
    ToolDefinitionError,
    ToolExecutionError,
    ToolPermissionError,
    ToolRateLimitError,
    ToolRetryExhaustedError,
    ToolTetherError,
    ToolTimeoutError,
    ToolValidationError,
    UnsafeOperationError,
)
from .feedback import FeedbackStore
from .models import (
    AuditRecord,
    CachePolicy,
    ConcurrencyPolicy,
    DataSensitivity,
    ExecutionContext,
    ExecutionEnvironment,
    ExecutionIdentity,
    FeedbackRecord,
    ModelCandidate,
    ModelSelection,
    OptimizationMode,
    OptimizationPolicy,
    OptimizationProfile,
    OptimizationRecommendation,
    Outcome,
    PermissionDecision,
    PermissionDecisionType,
    PermissionRequest,
    Plugin,
    PolicyRule,
    RateLimitPolicy,
    RetryPolicy,
    RiskLevel,
    RuntimeConfig,
    RuntimeEvent,
    SideEffects,
    TelemetryRecord,
    TimeoutPolicy,
    ToolCall,
    ToolCapabilities,
    ToolError,
    ToolFingerprint,
    ToolInput,
    ToolMetadata,
    ToolOutput,
    ToolResult,
    ToolRisk,
    ToolSpec,
)
from .optimizer import Optimizer, select_model
from .policy import CallableApprovalHandler, NonInteractiveApprovalHandler, Policy
from .registry import AdapterRegistry, ToolRegistry
from .runtime import Runtime, RuntimeBoundTool, current_execution
from .storage import SQLiteStorage
from .tool import BaseTool, Tool, ensure_tool, tool

__all__ = [
    "AdapterError",
    "AdapterRegistry",
    "AuditRecord",
    "BaseTool",
    "CachePolicy",
    "CallableApprovalHandler",
    "ConcurrencyPolicy",
    "DataSensitivity",
    "ExecutionContext",
    "ExecutionEnvironment",
    "ExecutionIdentity",
    "FeedbackRecord",
    "FeedbackStore",
    "MissingExtraError",
    "ModelCandidate",
    "ModelSelection",
    "NonInteractiveApprovalHandler",
    "OptimizationMode",
    "OptimizationPolicy",
    "OptimizationProfile",
    "OptimizationRecommendation",
    "Optimizer",
    "Outcome",
    "PermissionDecision",
    "PermissionDecisionType",
    "PermissionRequest",
    "Plugin",
    "Policy",
    "PolicyRule",
    "RateLimitPolicy",
    "RetryPolicy",
    "RiskLevel",
    "Runtime",
    "RuntimeBoundTool",
    "RuntimeConfig",
    "RuntimeEvent",
    "SQLiteStorage",
    "SideEffects",
    "StorageError",
    "TelemetryRecord",
    "TimeoutPolicy",
    "Tool",
    "ToolApprovalError",
    "ToolCall",
    "ToolCapabilities",
    "ToolDefinitionError",
    "ToolError",
    "ToolExecutionError",
    "ToolFingerprint",
    "ToolInput",
    "ToolMetadata",
    "ToolOutput",
    "ToolPermissionError",
    "ToolRateLimitError",
    "ToolRegistry",
    "ToolResult",
    "ToolRetryExhaustedError",
    "ToolRisk",
    "ToolSpec",
    "ToolTetherError",
    "ToolTimeoutError",
    "ToolValidationError",
    "UnsafeOperationError",
    "__version__",
    "current_execution",
    "ensure_tool",
    "select_model",
    "tool",
]
